//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantic.Reporting.Windows.Common.Internal.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantic.Reporting.Windows.Common.Internal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The content property must be an Accordion. 的本地化字符串。
        /// </summary>
        internal static string AccordionDragDropTarget_OnContentChanged_ContentMustBeAnAccordion {
            get {
                return ResourceManager.GetString("AccordionDragDropTarget_OnContentChanged_ContentMustBeAnAccordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AnchorMargin value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_AnchorMargin_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_AnchorMargin_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaximumMovingDistance value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MaximumMovingDistance_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MaximumMovingDistance_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinimumMovingDistance value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MinimumMovingDistance_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MinimumMovingDistance_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MovingStep value must be in range from 1 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MovingStep_ValueMustBeInRange1To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MovingStep_ValueMustBeInRange1To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string Automation_LegendClassName {
            get {
                return ResourceManager.GetString("Automation_LegendClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend Item 的本地化字符串。
        /// </summary>
        internal static string Automation_LegendItemClassName {
            get {
                return ResourceManager.GetString("Automation_LegendItemClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}K 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E03_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E03_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thousands 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E03_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E03_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E04_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E04_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E04_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E04_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E05_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E05_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E05_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E05_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}M 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E06_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E06_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Millions 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E06_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E06_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E07_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E07_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E07_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E07_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E08_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E08_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E08_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E08_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}bn 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E09_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E09_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billions 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E09_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E09_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E10_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E10_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E10_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E10_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E11_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E11_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E11_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E11_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}T 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E12_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E12_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trillions 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E12_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E12_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E13_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E13_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E13_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E13_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E14_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E14_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E14_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E14_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E15_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E15_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E15_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E15_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E16_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E16_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E16_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E16_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E17_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E17_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E17_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E17_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E18_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E18_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E18_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E18_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E19_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E19_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E19_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E19_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E20_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E20_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E20_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E20_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E21_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E21_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E21_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E21_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E22_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E22_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E22_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E22_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E23_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E23_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E23_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E23_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E24_LabelFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E24_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_E24_Title {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_E24_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0}) 的本地化字符串。
        /// </summary>
        internal static string DisplayUnitSystem_TitleFormat {
            get {
                return ResourceManager.GetString("DisplayUnitSystem_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removal by index is not supported. 的本地化字符串。
        /// </summary>
        internal static string DragDropTarget_RemoveItemAtIndex_RemovalByIndexNotSupported {
            get {
                return ResourceManager.GetString("DragDropTarget_RemoveItemAtIndex_RemovalByIndexNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content property must be a ListBox. 的本地化字符串。
        /// </summary>
        internal static string ListBoxDragDropTarget_OnContentChanged_ContentMustBeAListBox {
            get {
                return ResourceManager.GetString("ListBoxDragDropTarget_OnContentChanged_ContentMustBeAListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum value must be larger than or equal to the minimum value. 的本地化字符串。
        /// </summary>
        internal static string Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue {
            get {
                return ResourceManager.GetString("Range_ctor_MaximumValueMustBeLargerThanOrEqualToMinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read the Maximum of an empty range. 的本地化字符串。
        /// </summary>
        internal static string Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Maximum_CannotReadTheMaximumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read the Minimum of an empty range. 的本地化字符串。
        /// </summary>
        internal static string Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange {
            get {
                return ResourceManager.GetString("Range_get_Minimum_CannotReadTheMinimumOfAnEmptyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0},{1}] 的本地化字符串。
        /// </summary>
        internal static string Range_ToString_Data {
            get {
                return ResourceManager.GetString("Range_ToString_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Range 的本地化字符串。
        /// </summary>
        internal static string Range_ToString_NoData {
            get {
                return ResourceManager.GetString("Range_ToString_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range end 的本地化字符串。
        /// </summary>
        internal static string RangeSlider_End {
            get {
                return ResourceManager.GetString("RangeSlider_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range middle 的本地化字符串。
        /// </summary>
        internal static string RangeSlider_Middle {
            get {
                return ResourceManager.GetString("RangeSlider_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Range start 的本地化字符串。
        /// </summary>
        internal static string RangeSlider_Start {
            get {
                return ResourceManager.GetString("RangeSlider_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t reset enumerator. Reset dispenser instead. 的本地化字符串。
        /// </summary>
        internal static string ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead {
            get {
                return ResourceManager.GetString("ResourceDictionaryEnumerator_CantResetEnumeratorResetDispenserInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content property must of type TreeView. 的本地化字符串。
        /// </summary>
        internal static string TreeViewDragDropTarget_set_Content_ContentMustBeATreeView {
            get {
                return ResourceManager.GetString("TreeViewDragDropTarget_set_Content_ContentMustBeATreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of the event handler must be DragEventHandler. 的本地化字符串。
        /// </summary>
        internal static string UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeDragEventHandler {
            get {
                return ResourceManager.GetString("UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeDragEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of the event handler must be GiveFeedbackEventHandler. 的本地化字符串。
        /// </summary>
        internal static string UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeGiveFeedbackEventHandler {
            get {
                return ResourceManager.GetString("UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeGiveFeedbackEventHandle" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of the event handler must be QueryContinueDragEventHandler. 的本地化字符串。
        /// </summary>
        internal static string UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeQueryContinueDragEventHandler {
            get {
                return ResourceManager.GetString("UIElementExtendedRoutedEventExtensions_TypeOfHandlerMustBeQueryContinueDragEventH" +
                        "andler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attempt to insert a duplicate item. 的本地化字符串。
        /// </summary>
        internal static string UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem {
            get {
                return ResourceManager.GetString("UniqueObservableCollection_InvalidAttemptToInsertADuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot disable updates on not commited UpdateSession. Call EndUpdates first. 的本地化字符串。
        /// </summary>
        internal static string UpdateSession_DisableUpdates_Invalid_Call_Point {
            get {
                return ResourceManager.GetString("UpdateSession_DisableUpdates_Invalid_Call_Point", resourceCulture);
            }
        }
    }
}
