//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantic.Reporting.Windows.Chart.Internal.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantic.Reporting.Windows.Chart.Internal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AnchorMargin value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_AnchorMargin_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_AnchorMargin_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaximumMovingDistance value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MaximumMovingDistance_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MaximumMovingDistance_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinimumMovingDistance value must be in range from 0 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MinimumMovingDistance_ValueMustBeInRange0To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MinimumMovingDistance_ValueMustBeInRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MovingStep value must be in range from 1 to 1000. 的本地化字符串。
        /// </summary>
        internal static string AnchorPanel_MovingStep_ValueMustBeInRange1To1000 {
            get {
                return ResourceManager.GetString("AnchorPanel_MovingStep_ValueMustBeInRange1To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Area 的本地化字符串。
        /// </summary>
        internal static string Automation_ChartAreaClassName {
            get {
                return ResourceManager.GetString("Automation_ChartAreaClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Point 的本地化字符串。
        /// </summary>
        internal static string Automation_DataPointClassName {
            get {
                return ResourceManager.GetString("Automation_DataPointClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Series 的本地化字符串。
        /// </summary>
        internal static string Automation_SeriesClassName {
            get {
                return ResourceManager.GetString("Automation_SeriesClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot determine the size of an axis without an orientation. 的本地化字符串。
        /// </summary>
        internal static string Axis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone {
            get {
                return ResourceManager.GetString("Axis_GetLength_CannotDetermineTheLengthOfAnAxisWithAnOrientationOfNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis &apos;{0}&apos; cannot plot values of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AxisCannotPlotValuesOfType {
            get {
                return ResourceManager.GetString("AxisCannotPlotValuesOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axis &apos;{0}&apos; has uncompatible orientation with series &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AxisUncompatibleOrientation {
            get {
                return ResourceManager.GetString("AxisUncompatibleOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemSource cannot be assigned when the custom TreeSource is used. 的本地化字符串。
        /// </summary>
        internal static string CategoryScale_ItemSourceCannotBeSetWithTheCustomTreeSource {
            get {
                return ResourceManager.GetString("CategoryScale_ItemSourceCannotBeSetWithTheCustomTreeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the CategoryScale.ContentBinding before setting the ItemSource. 的本地化字符串。
        /// </summary>
        internal static string CategoryScale_SetContentBindingBeforeSettingItemSource {
            get {
                return ResourceManager.GetString("CategoryScale_SetContentBindingBeforeSettingItemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the CategoryScale.KeyBinding before setting the ItemSource. 的本地化字符串。
        /// </summary>
        internal static string CategoryScale_SetKeyBindingBeforeSettingItemSource {
            get {
                return ResourceManager.GetString("CategoryScale_SetKeyBindingBeforeSettingItemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The VirtualizationHelper must be set before the ItemSource. 的本地化字符串。
        /// </summary>
        internal static string CategoryScale_VirtuizationHelperMustBeSetBeforeItemSource {
            get {
                return ResourceManager.GetString("CategoryScale_VirtuizationHelperMustBeSetBeforeItemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axes collection setter is not supported. 的本地化字符串。
        /// </summary>
        internal static string Chart_Axes_SetterNotSupported {
            get {
                return ResourceManager.GetString("Chart_Axes_SetterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanent axes cannot be removed from the collection. 的本地化字符串。
        /// </summary>
        internal static string ChartAreaAxesCollection_InvalidAttemptToRemovePermanentAxis {
            get {
                return ResourceManager.GetString("ChartAreaAxesCollection_InvalidAttemptToRemovePermanentAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An axis cannot be removed from a series host when one or more hosted series is listening to it. 的本地化字符串。
        /// </summary>
        internal static string ChartAreaAxesCollection_RemoveItem_AxisCannotBeRemovedWhenOneOrMoreSeriesAreListeningToIt {
            get {
                return ResourceManager.GetString("ChartAreaAxesCollection_RemoveItem_AxisCannotBeRemovedWhenOneOrMoreSeriesAreListe" +
                        "ningToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataPoint details 的本地化字符串。
        /// </summary>
        internal static string DataPointDetailsScreenReaderContent {
            get {
                return ResourceManager.GetString("DataPointDetailsScreenReaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataPoint is highlighted 的本地化字符串。
        /// </summary>
        internal static string DataPointHighlightedScreenReaderContent {
            get {
                return ResourceManager.GetString("DataPointHighlightedScreenReaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Point series cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string DataPointSeriesCannotBeChanged {
            get {
                return ResourceManager.GetString("DataPointSeriesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMM dd 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_DayLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_DayLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMM dd, htt 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_HourLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_HourLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hh:mm:ss.fff tt 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_MillisecondLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_MillisecondLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hh:mm tt 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_MinuteLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_MinuteLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMM yyyy 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_MonthLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_MonthLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_SecondLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_SecondLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMM dd 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_WeekLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_WeekLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy 的本地化字符串。
        /// </summary>
        internal static string DateTimeScale_YearLabelFormat {
            get {
                return ResourceManager.GetString("DateTimeScale_YearLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to set Edge property to an invalid value. 的本地化字符串。
        /// </summary>
        internal static string EdgePanel_OnEdgePropertyChanged {
            get {
                return ResourceManager.GetString("EdgePanel_OnEdgePropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s CrossingPosition must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_CrossingPositionOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_CrossingPositionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s DataRange must have positive Minimum and Maximum. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_DataRangeOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_DataRangeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic base must be a positive number greater than 1. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_LogarithmicBaseOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_LogarithmicBaseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s Maximum must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_MaximumOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_MaximumOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s Minimum must be a positive number.  的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_MinimumOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_MinimumOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s ViewMaximum must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_ViewMaximumOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_ViewMaximumOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logarithmic scale&apos;s ViewMinimum must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string LogarithmicScale_ViewMinimumOutOfRange {
            get {
                return ResourceManager.GetString("LogarithmicScale_ViewMinimumOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marker size must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string Marker_size_must_be_a_positive_number {
            get {
                return ResourceManager.GetString("Marker_size_must_be_a_positive_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play axis play 的本地化字符串。
        /// </summary>
        internal static string PlayAxisPlayButtonScreenReaderContent {
            get {
                return ResourceManager.GetString("PlayAxisPlayButtonScreenReaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data value type is not supported by the scale. 的本地化字符串。
        /// </summary>
        internal static string Scale_DataValueTypeOutOfRange {
            get {
                return ResourceManager.GetString("Scale_DataValueTypeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provided view range is empty ({0}-{1}). 的本地化字符串。
        /// </summary>
        internal static string Scale_ViewRangeIsEmpty {
            get {
                return ResourceManager.GetString("Scale_ViewRangeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provided view range has a Minimum is greater than Maximum ({0}-{1}). 的本地化字符串。
        /// </summary>
        internal static string Scale_ViewRangeIsReverse {
            get {
                return ResourceManager.GetString("Scale_ViewRangeIsReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series overlap must be in range from -1 to 1. 的本地化字符串。
        /// </summary>
        internal static string Series_overlap_must_be_in_range_from_Minus1_to_1 {
            get {
                return ResourceManager.GetString("Series_overlap_must_be_in_range_from_Minus1_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series point gap width must be in range from 0 to 1. 的本地化字符串。
        /// </summary>
        internal static string Series_point_gap_width_must_be_in_range_from_0_to_1 {
            get {
                return ResourceManager.GetString("Series_point_gap_width_must_be_in_range_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series point pixel width must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string Series_point_width_must_be_a_positive_number {
            get {
                return ResourceManager.GetString("Series_point_width_must_be_a_positive_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series is {0} 的本地化字符串。
        /// </summary>
        internal static string SeriesScreenReaderLabel {
            get {
                return ResourceManager.GetString("SeriesScreenReaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The StrokeThickness property value can not be a negative number. 的本地化字符串。
        /// </summary>
        internal static string TheStrokeThicknessPropertyValueCannotBeANegativeNumber {
            get {
                return ResourceManager.GetString("TheStrokeThicknessPropertyValueCannotBeANegativeNumber", resourceCulture);
            }
        }
    }
}
